version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10.0.10.182:8100:8100"  # HTTP port
      - "10.0.10.182:8443:8443"  # HTTPS port
    volumes:
      - ./app:/app/app
      - ./data:/app/data
      - ./models:/app/models
      # No need to mount ./certs since the certificates are already in ./app/certs
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - SSL_KEYFILE=/app/certs/privkey.pem
      - SSL_CERTFILE=/app/certs/fullchain.pem
      - PORT=8100
      - SSL_PORT=8443
    
  nginx:
    image: nginx:alpine
    ports:
      - "10.0.10.182:8301:83"  # Changed from 8443 to 9443
      - "10.0.10.182:8081:80"   # Using 8081 for HTTP
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - app
    restart: unless-stopped