version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10.0.10.182:8100:8100"
    volumes:
      - ./app:/app/app
      - ./data:/app/data
      - ./models:/app/models
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8100 --reload"